export type Branch = {
  name: string;
  state: string;
  address: string;
  phone: string;
  whatsapp: string;
  hours: string;
  services: string[];
  mapsUrl: string;
};

/**
 * Quick-pick groups shown as buttons beside the locator, for the two areas
 * visitors most often arrive in. Branches are listed by name because the
 * grouping is editorial — "near the airport" is not something the state or
 * address fields can answer.
 */
export type BranchZone = {
  id: string;
  label: string;
  description: string;
  branchNames: string[];
};

export const branchZones: BranchZone[] = [
  {
    id: "klia",
    label: "Nearby KLIA Airport",
    description: "Exchange on arrival or before you fly",
    // "Ampang" is the NZ Curry House @ KLCC counter, kept under its existing name.
    branchNames: ["Petronas KLIA", "Shell KLIA", "Mitsui Outlet Park"],
  },
  {
    id: "kl-city",
    label: "KL City Centre",
    description: "In the heart of Kuala Lumpur",
    branchNames: ["Ampang", "Bukit Bintang", "Menara Kuala Lumpur"],
  },
];

export const states = [
  "Kuala Lumpur",
  "Selangor",
  "Kedah",
  "Perak",
  "Penang",
  "Johor",
  "Malacca",
  "Negeri Sembilan",
  "Sabah",
  "Sarawak",
] as const;

export const branches: Branch[] = [
  {
    name: "Ampang",
    state: "Kuala Lumpur",
    address: "Nz Curry House @ Klcc, Lot 42, Jalan Ampang, Kampung Baru, 50450 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur",
    phone: "+60 173013811",
    whatsapp: "https://wa.me/60173013811",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Nz+Curry+House+%40+Klcc%2C+Lot+42%2C+Jalan+Ampang%2C+Kampung+Baru%2C+50450+Kuala+Lumpur%2C+Wilayah+Persekutuan+Kuala+Lumpur",
  },
  {
    name: "Bukit Bintang",
    state: "Kuala Lumpur",
    address: "Hotel Ambassador, 44, Jalan Sultan Ismail, 50250 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur",
    phone: "+60 1158715446",
    whatsapp: "https://wa.me/601158715446",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Hotel+Ambassador%2C+44%2C+Jalan+Sultan+Ismail%2C+50250+Kuala+Lumpur%2C+Wilayah+Persekutuan+Kuala+Lumpur",
  },
  {
    name: "Giant Setapak",
    state: "Kuala Lumpur",
    address: "Lot G07, Giant Hypermarket Setapak, NO. 5, Jalan Kilang Off Jalan Genting Kelang, Taman Danau Kota, 53300 Setapak, Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur",
    phone: "+60 1156514252",
    whatsapp: "https://wa.me/601156514252",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Lot+G07%2C+Giant+Hypermarket+Setapak%2C+NO.+5%2C+Jalan+Kilang+Off+Jalan+Genting+Kelang%2C+Taman+Danau+Kota%2C+53300+Setapak%2C+Kuala+Lumpur%2C+Wilayah+Persekutuan+Kuala+Lumpur",
  },
  {
    name: "Menara Kuala Lumpur",
    state: "Kuala Lumpur",
    address: "Kiosk 7 Upper Ground Floor (UGF), Menara Kuala Lumpur, No.2 Jalan Punchak, Off Jalan P.ramlee, 50250 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur",
    phone: "+60 178895811",
    whatsapp: "https://wa.me/60178895811",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Kiosk+7+Upper+Ground+Floor+%28UGF%29%2C+Menara+Kuala+Lumpur%2C+No.2+Jalan+Punchak%2C+Off+Jalan+P.ramlee%2C+50250+Kuala+Lumpur%2C+Wilayah+Persekutuan+Kuala+Lumpur",
  },
  {
    name: "Rampai Business Park",
    state: "Kuala Lumpur",
    address: "Hasani Books, 2, Jalan Rampai Niaga 4, Rampai Business Park, Setapak, 53300 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur",
    phone: "+60 176244492",
    whatsapp: "https://wa.me/60176244492",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Hasani+Books%2C+2%2C+Jalan+Rampai+Niaga+4%2C+Rampai+Business+Park%2C+Setapak%2C+53300+Kuala+Lumpur%2C+Wilayah+Persekutuan+Kuala+Lumpur",
  },
  {
    name: "Management & Operations Center",
    state: "Kuala Lumpur",
    address: "33,33-1 and 35,35-1 (Ground and First Floor), Jalan Seri Rejang 3, Pusat Industri Sri Rampai, 53300 Setapak, Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur",
    phone: "+60 341319809",
    whatsapp: "https://wa.me/60341319809",
    hours: "Mon–Sat",
    services: ["Corporate Office"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=33%2C33-1+and+35%2C35-1+%28Ground+and+First+Floor%29%2C+Jalan+Seri+Rejang+3%2C+Pusat+Industri+Sri+Rampai%2C+53300+Setapak%2C+Kuala+Lumpur%2C+Wilayah+Persekutuan+Kuala+Lumpur",
  },
  {
    name: "Rk Success SDN BHD",
    state: "Kuala Lumpur",
    address: "Hasani Books, Setapak Central, Lot No. F-52, First Floor, No. 67, Jalan Taman Ibu Kota, Taman Danau Kota, 53300 Setapak, Wilayah Persekutuan Kuala Lumpur.",
    phone: "+60 1113043493",
    whatsapp: "https://wa.me/601113043493",
    hours: "Mon–Sun (Daily)",
    services: ["Agents", "Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Hasani+Books%2C+Setapak+Central%2C+Lot+No.+F-52%2C+First+Floor%2C+No.+67%2C+Jalan+Taman+Ibu+Kota%2C+Taman+Danau+Kota%2C+53300+Setapak%2C+Wilayah+Persekutuan+Kuala+Lumpur.",
  },
  {
    name: "Petronas KLIA",
    state: "Selangor",
    address: "Petronas Service Station, Lot PT 3906, Klia1 Inbound, Jalan Terminal KLIA, 64000 Sepang, Selangor",
    phone: "+60 164741137",
    whatsapp: "https://wa.me/60164741137",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Petronas+Service+Station%2C+Lot+PT+3906%2C+Klia1+Inbound%2C+Jalan+Terminal+KLIA%2C+64000+Sepang%2C+Selangor",
  },
  {
    name: "Mitsui Outlet Park",
    state: "Selangor",
    address: "Kiosk 9, Ground Foor, Mitsui Outlet Park KLIA Sepang, Persiaran Komersial, 64000 KLIA Sepang, Selangor",
    phone: "+60 172775811",
    whatsapp: "https://wa.me/60172775811",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Kiosk+9%2C+Ground+Foor%2C+Mitsui+Outlet+Park+KLIA+Sepang%2C+Persiaran+Komersial%2C+64000+KLIA+Sepang%2C+Selangor",
  },
  {
    name: "Shell KLIA",
    state: "Selangor",
    address: "Shell Service Station Site ID 2441, Lot 1 PT3, Jalan Lapangan Terbang KLIA, 64000 Sepang, Selangor",
    phone: "+60 133323811",
    whatsapp: "https://wa.me/60133323811",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Shell+Service+Station+Site+ID+2441%2C+Lot+1+PT3%2C+Jalan+Lapangan+Terbang+KLIA%2C+64000+Sepang%2C+Selangor",
  },
  {
    name: "YBH World Link SDN BHD",
    state: "Selangor",
    address: "31A, Jalan Pekan Kg. Baru Kundang, 48020 Rawang, Selangor",
    phone: "+60 1116663360",
    whatsapp: "https://wa.me/601116663360",
    hours: "Mon–Sun (Daily)",
    services: ["Agents", "Money Transfer"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=31A%2C+Jalan+Pekan+Kg.+Baru+Kundang%2C+48020+Rawang%2C+Selangor",
  },
  {
    name: "Jejantas Gemilang 232 SDN BHD",
    state: "Selangor",
    address: "18, Jalan Pusat BCH 1/1, Bandar Country Homes, 48000 Rawang, Selangor",
    phone: "+60 124032382",
    whatsapp: "https://wa.me/60124032382",
    hours: "Tue–Sun",
    services: ["Agents", "Money Transfer"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=18%2C+Jalan+Pusat+BCH+1%2F1%2C+Bandar+Country+Homes%2C+48000+Rawang%2C+Selangor",
  },
  {
    name: "YS Plus Network SDN BHD",
    state: "Selangor",
    address: "No. 30 Jalan SD 1, Taman Sekinchan Damai, 45400 Sekinchan, Selangor.",
    phone: "+60 133447687",
    whatsapp: "https://wa.me/60133447687",
    hours: "Mon–Sun (Daily)",
    services: ["Agents", "Money Transfer"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=No.+30+Jalan+SD+1%2C+Taman+Sekinchan+Damai%2C+45400+Sekinchan%2C+Selangor.",
  },
  {
    name: "Riz Multibiz SDN BHD",
    state: "Selangor",
    address: "No. 180, Jalan Bunga Pekan, 42700 Banting, Selangor",
    phone: "+60 108636373",
    whatsapp: "https://wa.me/60108636373",
    hours: "Mon–Sun (Daily)",
    services: ["Agents", "Money Transfer"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=No.+180%2C+Jalan+Bunga+Pekan%2C+42700+Banting%2C+Selangor",
  },
  {
    name: "A3",
    state: "Kedah",
    address: "A3, Jalan Kampung Baru, 08000 Sungai Petani, Kedah",
    phone: "+60 1158715417",
    whatsapp: "https://wa.me/601158715417",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=A3%2C+Jalan+Kampung+Baru%2C+08000+Sungai+Petani%2C+Kedah",
  },
  {
    name: "Amanjaya",
    state: "Kedah",
    address: "No 29, Jalan Jati 1/1, Pusat Perniagaan Amanjaya, 08000 Sungai Petani, Kedah",
    phone: "+60 1158715419",
    whatsapp: "https://wa.me/601158715419",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=No+29%2C+Jalan+Jati+1%2F1%2C+Pusat+Perniagaan+Amanjaya%2C+08000+Sungai+Petani%2C+Kedah",
  },
  {
    name: "Astana",
    state: "Kedah",
    address: "1, Taman Seri Astana, Fasa 1, Jalan Langgar, 05460 Alor Setar, Kedah",
    phone: "+60 1158715428",
    whatsapp: "https://wa.me/601158715428",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=1%2C+Taman+Seri+Astana%2C+Fasa+1%2C+Jalan+Langgar%2C+05460+Alor+Setar%2C+Kedah",
  },
  {
    name: "Ban Bee",
    state: "Kedah",
    address: "No 25C, Bangunan Ban Bee, Jalan Kampung Baru, 08000 Sungai Petani, Kedah",
    phone: "+60 127861137",
    whatsapp: "https://wa.me/60127861137",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=No+25C%2C+Bangunan+Ban+Bee%2C+Jalan+Kampung+Baru%2C+08000+Sungai+Petani%2C+Kedah",
  },
  {
    name: "Central Square",
    state: "Kedah",
    address: "Lot Gf-42, Ground Floor, Central Square, Jalan Kampung Baru, 08000 Sungai Petani, Kedah",
    phone: "+60 1158715418",
    whatsapp: "https://wa.me/601158715418",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Lot+Gf-42%2C+Ground+Floor%2C+Central+Square%2C+Jalan+Kampung+Baru%2C+08000+Sungai+Petani%2C+Kedah",
  },
  {
    name: "Changlun",
    state: "Kedah",
    address: "Petronas Service Station, Lot 1993 E1, Changlun, 06010 Changlun, Kedah",
    phone: "+60 1158715434",
    whatsapp: "https://wa.me/601158715434",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Petronas+Service+Station%2C+Lot+1993+E1%2C+Changlun%2C+06010+Changlun%2C+Kedah",
  },
  {
    name: "Gurun",
    state: "Kedah",
    address: "Lot 11, Jerai Plaza, Taman Jerai Maju, 08300 Gurun, Kedah",
    phone: "+60 1158715426",
    whatsapp: "https://wa.me/601158715426",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Lot+11%2C+Jerai+Plaza%2C+Taman+Jerai+Maju%2C+08300+Gurun%2C+Kedah",
  },
  {
    name: "Jitra",
    state: "Kedah",
    address: "No 250A, Jalan PJ 2/2, Pekan Jitra 2, Jalan Jitra, Kampung Tok Kesop, 06000 Jitra, Kedah",
    phone: "+60 1158715427",
    whatsapp: "https://wa.me/601158715427",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=No+250A%2C+Jalan+PJ+2%2F2%2C+Pekan+Jitra+2%2C+Jalan+Jitra%2C+Kampung+Tok+Kesop%2C+06000+Jitra%2C+Kedah",
  },
  {
    name: "Kuah Langkawi",
    state: "Kedah",
    address: "No 2, Jalan Persiaran Putra, 07000 Kuah, Langkawi, Kedah",
    phone: "+60 103964811",
    whatsapp: "https://wa.me/60103964811",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=No+2%2C+Jalan+Persiaran+Putra%2C+07000+Kuah%2C+Langkawi%2C+Kedah",
  },
  {
    name: "Kulim",
    state: "Kedah",
    address: "Lot Gf-26, Landmark Central Shopping Centre, 09000 Kulim, Kedah",
    phone: "+60 1158715447",
    whatsapp: "https://wa.me/601158715447",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Lot+Gf-26%2C+Landmark+Central+Shopping+Centre%2C+09000+Kulim%2C+Kedah",
  },
  {
    name: "Head Office",
    state: "Kedah",
    address: "25C Bangunan Ban Bee, Jalan Kampung Baru, 08000 Sungai Petani, Kedah.",
    phone: "+60 44213811",
    whatsapp: "https://wa.me/6044213811",
    hours: "Mon–Sat",
    services: ["Corporate Office"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=25C+Bangunan+Ban+Bee%2C+Jalan+Kampung+Baru%2C+08000+Sungai+Petani%2C+Kedah.",
  },
  {
    name: "Jhou Links SDN BHD",
    state: "Kedah",
    address: "No. 32A Tingkat Bawah Susur Alamanda 4, Pusat Perniagaan Alamanda, 08200 Sik, Kedah",
    phone: "+60 164759472",
    whatsapp: "https://wa.me/60164759472",
    hours: "Mon–Sun (Daily)",
    services: ["Agents", "Money Transfer"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=No.+32A+Tingkat+Bawah+Susur+Alamanda+4%2C+Pusat+Perniagaan+Alamanda%2C+08200+Sik%2C+Kedah",
  },
  {
    name: "Aeon Seri Manjung",
    state: "Perak",
    address: "Lot G-75, Aeon Seri Manjung Shopping Centre, Pusat Perniagaan Manjung Point 3, 32040 Seri Manjung, Perak",
    phone: "+60 175009436",
    whatsapp: "https://wa.me/60175009436",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Lot+G-75%2C+Aeon+Seri+Manjung+Shopping+Centre%2C+Pusat+Perniagaan+Manjung+Point+3%2C+32040+Seri+Manjung%2C+Perak",
  },
  {
    name: "Ayer Tawar",
    state: "Perak",
    address: "NO. 301, Jalan Besar, 32400 Ayer Tawar, Perak",
    phone: "+60 1162825004",
    whatsapp: "https://wa.me/601162825004",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=NO.+301%2C+Jalan+Besar%2C+32400+Ayer+Tawar%2C+Perak",
  },
  {
    name: "Batu Gajah",
    state: "Perak",
    address: "Lot No 6 & 7, Pasaraya TF Value Mart, Jalan Baharu, Bandar Baharu Batu Gajah, 30200 Batu Gajah, Perak",
    phone: "+60 1158715392",
    whatsapp: "https://wa.me/601158715392",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Lot+No+6+%26+7%2C+Pasaraya+TF+Value+Mart%2C+Jalan+Baharu%2C+Bandar+Baharu+Batu+Gajah%2C+30200+Batu+Gajah%2C+Perak",
  },
  {
    name: "Ipoh",
    state: "Perak",
    address: "No 42, Jalan Dato Onn Jaafar, Kampung Jawa, 30300 Ipoh, Perak",
    phone: "+60 1158715387",
    whatsapp: "https://wa.me/601158715387",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=No+42%2C+Jalan+Dato+Onn+Jaafar%2C+Kampung+Jawa%2C+30300+Ipoh%2C+Perak",
  },
  {
    name: "Lekir",
    state: "Perak",
    address: "Jalan 5, NO. 18 Kampung Batu Sepuluh Lekir, 32000 Sitiawan, Perak",
    phone: "+60 1158715379",
    whatsapp: "https://wa.me/601158715379",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Jalan+5%2C+NO.+18+Kampung+Batu+Sepuluh+Lekir%2C+32000+Sitiawan%2C+Perak",
  },
  {
    name: "Pantai Remis",
    state: "Perak",
    address: "NO. 56, Jalan Damar Laut, 34900 Pantai Remis, Perak",
    phone: "+60 1158715273",
    whatsapp: "https://wa.me/601158715273",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=NO.+56%2C+Jalan+Damar+Laut%2C+34900+Pantai+Remis%2C+Perak",
  },
  {
    name: "Sitiawan",
    state: "Perak",
    address: "Lot 20, Tingkat Bawah, Bangunan Luth, Jalan Lumut, 32000 Sitiawan, Perak",
    phone: "+60 175009745",
    whatsapp: "https://wa.me/60175009745",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Lot+20%2C+Tingkat+Bawah%2C+Bangunan+Luth%2C+Jalan+Lumut%2C+32000+Sitiawan%2C+Perak",
  },
  {
    name: "Tambun",
    state: "Perak",
    address: "NO. 46, Ground Floor, Persiaran SC1 2/1, Sunway City Ipoh, 31150 Ipoh, Perak",
    phone: "+60 1135347735",
    whatsapp: "https://wa.me/601135347735",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=NO.+46%2C+Ground+Floor%2C+Persiaran+SC1+2%2F1%2C+Sunway+City+Ipoh%2C+31150+Ipoh%2C+Perak",
  },
  {
    name: "Tasek",
    state: "Perak",
    address: "Econsave Tasek, Unit No Ts07, Lot 111983 Jalan Kuala Kangsar, 31200 Ipoh, Perak",
    phone: "+60 108380735",
    whatsapp: "https://wa.me/60108380735",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Econsave+Tasek%2C+Unit+No+Ts07%2C+Lot+111983+Jalan+Kuala+Kangsar%2C+31200+Ipoh%2C+Perak",
  },
  {
    name: "FWJ Network SDN BHD",
    state: "Perak",
    address: "No. 32, Jalan Besar, 36700 Langkap, Perak",
    phone: "+60 1135776160",
    whatsapp: "https://wa.me/601135776160",
    hours: "Mon–Sun (Daily)",
    services: ["Agents", "Money Transfer"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=No.+32%2C+Jalan+Besar%2C+36700+Langkap%2C+Perak",
  },
  {
    name: "Hooi Han Links SDN BHD",
    state: "Perak",
    address: "197A, Jalan Besar, Sungai Kerang, 34800 Trong, Perak",
    phone: "+60 1160551988",
    whatsapp: "https://wa.me/601160551988",
    hours: "Mon–Sun (Daily)",
    services: ["Agents", "Money Transfer"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=197A%2C+Jalan+Besar%2C+Sungai+Kerang%2C+34800+Trong%2C+Perak",
  },
  {
    name: "VM Connections SDN BHD",
    state: "Perak",
    address: "663, Taman Kota Jaya, 34700 Simpang, Perak",
    phone: "+60 195455545",
    whatsapp: "https://wa.me/60195455545",
    hours: "Mon–Sat",
    services: ["Agents", "Money Transfer"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=663%2C+Taman+Kota+Jaya%2C+34700+Simpang%2C+Perak",
  },
  {
    name: "Bukit Minyak",
    state: "Penang",
    address: "No1, Tingkat, Aeon Big Shopping Centre, No G8, Jalan Bukit Minyak 9, Taman Bukit Minyak, 14000 Bukit Mertajam, Pulau Pinang",
    phone: "+60 45082811",
    whatsapp: "https://wa.me/6045082811",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=No1%2C+Tingkat%2C+Aeon+Big+Shopping+Centre%2C+No+G8%2C+Jalan+Bukit+Minyak+9%2C+Taman+Bukit+Minyak%2C+14000+Bukit+Mertajam%2C+Pulau+Pinang",
  },
  {
    name: "Design Village",
    state: "Penang",
    address: "Kiosk No. KS-08A, Design Village Outlet Mall, Jalan Cassia Barat 2, 14110 Bandar Cassia, Pulau Pinang",
    phone: "+60 1158715437",
    whatsapp: "https://wa.me/601158715437",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Kiosk+No.+KS-08A%2C+Design+Village+Outlet+Mall%2C+Jalan+Cassia+Barat+2%2C+14110+Bandar+Cassia%2C+Pulau+Pinang",
  },
  {
    name: "Gurney Walk",
    state: "Penang",
    address: "Gurney Walk, NO. 18, Persiaran Gurney, 10250 Georgetown, Pulau Pinang",
    phone: "+60 187866086",
    whatsapp: "https://wa.me/60187866086",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Gurney+Walk%2C+NO.+18%2C+Persiaran+Gurney%2C+10250+Georgetown%2C+Pulau+Pinang",
  },
  {
    name: "Juru",
    state: "Penang",
    address: "1639 & 1640 Jalan Perusahaan Bukit Minyak, Taman Pelangi, 13600 Bukit Mertajam, Pulau Pinang",
    phone: "+60 1158715439",
    whatsapp: "https://wa.me/601158715439",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=1639+%26+1640+Jalan+Perusahaan+Bukit+Minyak%2C+Taman+Pelangi%2C+13600+Bukit+Mertajam%2C+Pulau+Pinang",
  },
  {
    name: "Prangin Mall",
    state: "Penang",
    address: "Lot 01 G/11, Tingkat Bawah,prangin Mall, 10100 Georgetown, Pulau Pinang",
    phone: "+60 143472311",
    whatsapp: "https://wa.me/60143472311",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Lot+01+G%2F11%2C+Tingkat+Bawah%2Cprangin+Mall%2C+10100+Georgetown%2C+Pulau+Pinang",
  },
  {
    name: "Simpang Ampat",
    state: "Penang",
    address: "No 17, Jalan Besar, Taman Tempua, 14100 Simpang Ampat, Pulau Pinang",
    phone: "+60 1158715435",
    whatsapp: "https://wa.me/601158715435",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=No+17%2C+Jalan+Besar%2C+Taman+Tempua%2C+14100+Simpang+Ampat%2C+Pulau+Pinang",
  },
  {
    name: "Sunway Carnival",
    state: "Penang",
    address: "B-k01, Sunway Carnival Mall, 3068 Jalan Todak, Pusat Seberang Jaya, 13700 Seberang Jaya, Pulau Pinang",
    phone: "+60 1158715242",
    whatsapp: "https://wa.me/601158715242",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=B-k01%2C+Sunway+Carnival+Mall%2C+3068+Jalan+Todak%2C+Pusat+Seberang+Jaya%2C+13700+Seberang+Jaya%2C+Pulau+Pinang",
  },
  {
    name: "Sunway Carnival 2",
    state: "Penang",
    address: "LG-K08A, Sunway Carnival Mall, Jalan Todak, Pusat Bandar Seberang Jaya, 13700 Seberang Jaya, Pulau Pinang",
    phone: "+60 1188885411",
    whatsapp: "https://wa.me/601188885411",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=LG-K08A%2C+Sunway+Carnival+Mall%2C+Jalan+Todak%2C+Pusat+Bandar+Seberang+Jaya%2C+13700+Seberang+Jaya%2C+Pulau+Pinang",
  },
  {
    name: "Pekan Nanas",
    state: "Johor",
    address: "Econsave Pekan Nanas, Lot 2665 & 2666, 81500 Pekan Nanas, Johor",
    phone: "+60 124511137",
    whatsapp: "https://wa.me/60124511137",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Econsave+Pekan+Nanas%2C+Lot+2665+%26+2666%2C+81500+Pekan+Nanas%2C+Johor",
  },
  {
    name: "Taman Daya",
    state: "Johor",
    address: "Econsave Taman Daya, PTD 124006, Jalan Nipah, Taman Daya, 81100 Johor Bahru, Johor",
    phone: "+60 124611137",
    whatsapp: "https://wa.me/60124611137",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Econsave+Taman+Daya%2C+PTD+124006%2C+Jalan+Nipah%2C+Taman+Daya%2C+81100+Johor+Bahru%2C+Johor",
  },
  {
    name: "Scy Mobile Tele SDN BHD",
    state: "Malacca",
    address: "1221, Jalan Seri Pelangi 1, Taman Seri Pelangi, 78000 Alor Gajah, Melaka",
    phone: "+60 122362856",
    whatsapp: "https://wa.me/60122362856",
    hours: "Mon–Sun (Daily)",
    services: ["Agents", "Money Transfer"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=1221%2C+Jalan+Seri+Pelangi+1%2C+Taman+Seri+Pelangi%2C+78000+Alor+Gajah%2C+Melaka",
  },
  {
    name: "Mh Harmony SDN BHD",
    state: "Negeri Sembilan",
    address: "No. 24, Jalan Besar Pasir Panjang, Port Dickson, 71250 Pasir Panjang, Negeri Sembilan",
    phone: "+60 138933226",
    whatsapp: "https://wa.me/60138933226",
    hours: "Mon–Sat",
    services: ["Agents", "Money Transfer"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=No.+24%2C+Jalan+Besar+Pasir+Panjang%2C+Port+Dickson%2C+71250+Pasir+Panjang%2C+Negeri+Sembilan",
  },
  {
    name: "Wisma Merdeka",
    state: "Sabah",
    address: "AG 08, Ground Floor, Phase 1, Wisma Merdeka, Jalan Tun Razak, 88000 Kota Kinabalu, Sabah",
    phone: "+60 174653811",
    whatsapp: "https://wa.me/60174653811",
    hours: "Mon–Sun (Daily)",
    services: ["Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=AG+08%2C+Ground+Floor%2C+Phase+1%2C+Wisma+Merdeka%2C+Jalan+Tun+Razak%2C+88000+Kota+Kinabalu%2C+Sabah",
  },
  {
    name: "MEM Money Express SDN BHD",
    state: "Sabah",
    address: "Block A, Lot 5, SEDCO Pekan Telupid, 89320 Telupid, Sabah",
    phone: "+60 168279907",
    whatsapp: "https://wa.me/60168279907",
    hours: "Mon–Sun (Daily)",
    services: ["Agents", "Money Transfer"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Block+A%2C+Lot+5%2C+SEDCO+Pekan+Telupid%2C+89320+Telupid%2C+Sabah",
  },
  {
    name: "Juhair Group SDN BHD",
    state: "Sabah",
    address: "Unit AG38, Ground Floor, Wisma Merdeka Phase 1, Jalan Tun Razak, 88000 Kota Kinabalu, Sabah",
    phone: "+60 1161112024",
    whatsapp: "https://wa.me/601161112024",
    hours: "Mon–Sun (Daily)",
    services: ["Agents", "Money Transfer", "Currency Exchange"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Unit+AG38%2C+Ground+Floor%2C+Wisma+Merdeka+Phase+1%2C+Jalan+Tun+Razak%2C+88000+Kota+Kinabalu%2C+Sabah",
  },
  {
    name: "Samkong Global SDN BHD",
    state: "Sarawak",
    address: "No. 38, Pasar Bau, Jalan Temenggong Salau, 94000 Bau, Sarawak",
    phone: "+60 177829133",
    whatsapp: "https://wa.me/60177829133",
    hours: "Mon–Sun (Daily)",
    services: ["Agents", "Money Transfer"],
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=No.+38%2C+Pasar+Bau%2C+Jalan+Temenggong+Salau%2C+94000+Bau%2C+Sarawak",
  },
];
